---
title: Reporte Migración CMSSW 9X 29-01-2018
layout: content
toc: true
---

# Reporte Migración CMSSW 9X 29-01-2018


Después de cuadrar los certificados de GRID (que me los habían revocado), 
requeridos para entrar a las plataformas DAS, 
en el reporte anterior se me sugirió modificar el query y quedo así

``` sh
dataset  dataset=/WJetsToLNu_HT-*/*/* release=CMSSW_9_*
```

el resultado en en das

[https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset++dataset%3D%2FWJetsToLNu_HT-*%2F*%2F*+release%3DCMSSW_9_*](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset++dataset%3D%2FWJetsToLNu_HT-*%2F*%2F*+release%3DCMSSW_9_*)

hice modificafiones de https://github.com/HENGEX/VLF_ANA/blob/cmssw-9.4.3/Dracarys/test/Submit_WJetsToLNu_HT.py para correr en crab 
pero por sugerencia de José estoy trabajando en https://github.com/HENGEX/VLF_ANA/blob/cmssw-9.4.3/Dracarys/test/ConfFile_cfg.py
para correrlo directamente con cmsRun

para correr con cmsRun necesito las rutas de los archivos con el protocolo root usando el servidor xrootd, para asuntos prácticos del query solo tome la primera entrada

Dataset: /WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall17NanoAOD-PUMoriond17_94X_mcRun2_asymptotic_v2-v1/NANOAODSIM
Creation time: 2018-01-16 15:59:47, Physics group: NoGroup, Release: CMSSW_9_4_2, Status: VALID, Tag: 94X_mcRun2_asymptotic_v2, Type: mc


y de esta entrada figuran los siguientes archivos ROOT

entrada:

[https://cmsweb.cern.ch/das/makepy?dataset=/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall17NanoAOD-PUMoriond17_94X_mcRun2_asymptotic_v2-v1/NANOAODSIM&instance=prod/global](https://cmsweb.cern.ch/das/makepy?dataset=/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall17NanoAOD-PUMoriond17_94X_mcRun2_asymptotic_v2-v1/NANOAODSIM&instance=prod/global)

archivos 
``` py
import FWCore.ParameterSet.Config as cms
maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles)
readFiles.extend( [
'/store/mc/RunIIFall17NanoAOD/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v2-v1/20000/12701488-C1FE-E711-8CD8-002481CFE642.root',
'/store/mc/RunIIFall17NanoAOD/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v2-v1/20000/2E70119E-D7FA-E711-BAE2-141877637B68.root',
'/store/mc/RunIIFall17NanoAOD/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v2-v1/20000/4A57638D-C1FE-E711-A482-ECB1D7B67E10.root',
'/store/mc/RunIIFall17NanoAOD/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v2-v1/20000/701D8A4F-D7FA-E711-956B-001EC94BA15D.root',
'/store/mc/RunIIFall17NanoAOD/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v2-v1/20000/8C850AC8-D7FA-E711-8074-0CC47AA99436.root',
'/store/mc/RunIIFall17NanoAOD/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v2-v1/20000/9CAD608D-C1FE-E711-B743-ECB1D7B67E10.root',
'/store/mc/RunIIFall17NanoAOD/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v2-v1/20000/E6BB1537-C3FA-E711-B19C-002590D4FBB6.root',
'/store/mc/RunIIFall17NanoAOD/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v2-v1/20000/F6635691-C1FE-E711-BB49-0CC47A5FC619.root' ] );
```




Bueno al correr cmsRun en el ConfFile_cfg modifica me encuentro con los siguientes problemas,
pero leyendo los wikis encuentro algunas cosas:

1)
Problema:
``` sh
ozapatam@lxplus012 python]$ cmsRun ConfFile_cfg2.py
----- Begin Fatal Exception 29-Jan-2018 21:28:43 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named ConfFile_cfg2.py
Exception Message:
python encountered the error: <type 'exceptions.ImportError'>
No module named TransientTrackBuilder_cfi
----- End Fatal Exception -------------------------------------------------
```

Solución:
en un wiki vi que hay un repositorio de plugins para cmssw https://github.com/cms-cvs-history
lo que hice fue buscar el plugin correcto y en la carpeta src del CMSSW se descarga par este caso https://github.com/cms-cvs-history/TrackingTools-TransientTrack
``` sh
cd CMSSW_9_4_3/src
git cms-addpkg TrackingTools/TransientTrack
scram b -j 10
```

2)
Problema:
``` sh
[ozapatam@lxplus108 test]$ cmsRun ConfFile_cfg2.py 
----- Begin Fatal Exception 29-Jan-2018 22:05:57 CET-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=XMLIdealGeometryESSource label='magfield'
Exception Message:
edm::FileInPath unable to find file MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /afs/cern.ch/user/o/ozapatam/CMSSW_9_4_3/src:/afs/cern.ch/user/o/ozapatam/CMSSW_9_4_3/external/slc6_amd64_gcc630/data:/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_3/src:/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_3/external/slc6_amd64_gcc630/data
Current directory is: /afs/cern.ch/user/o/ozapatam/CMSSW_9_4_3/src/VLF_ANA/Dracarys/test
----- End Fatal Exception -------------------------------------------------
```

Posible solución:
trate de aplicar la misma pero no funciono
``` sh
git cms-addpkg MagneticField/GeomBuilder
```

dice que no puede encontrar el archivo MagneticFieldVolumes_1_v7_large.xml lo raro es que si esta en el repo
https://github.com/cms-cvs-history/MagneticField-GeomBuilder/blob/master/data/MagneticFieldVolumes_1_v7_large.xml

lo que hice fue bajarlo y ponerlo a mano, igual para el https://raw.githubusercontent.com/cms-cvs-history/MagneticField-GeomBuilder/master/data/MagneticFieldVolumes_2_v7_large.xml  
por que sacaba error para ese archivo también.
``` sh
ozapatam@lxplus038 src]$ cd MagneticField/GeomBuilder/data/
[ozapatam@lxplus038 data]$ ls
MagneticFieldVolumes_160812_1.xml  MagneticFieldVolumes_160812_2.xml
[ozapatam@lxplus038 data]$ wget https://raw.githubusercontent.com/cms-cvs-history/MagneticField-GeomBuilder/master/data/MagneticFieldVolumes_1_v7_large.xml
[ozapatam@lxplus108 test]$ wget https://raw.githubusercontent.com/cms-cvs-history/MagneticField-GeomBuilder/master/data/MagneticFieldVolumes_2_v7_large.xml
```

esto parece funcionar y empieza a bajar los archivos pero aun tengo estos dos errores

``` sh
29-Jan-2018 22:16:54 CET  Successfully opened file root://xrootd-cms.infn.it//store/mc/RunIIFall17NanoAOD/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v2-v1/20000/12701488-C1FE-E711-8CD8-002481CFE642.root
29-Jan-2018 22:16:55 CET  Closed file root://xrootd-cms.infn.it//store/mc/RunIIFall17NanoAOD/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v2-v1/20000/12701488-C1FE-E711-8CD8-002481CFE642.root
----- Begin Fatal Exception 29-Jan-2018 22:16:55 CET-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   Additional Info:
      [a] Fatal Root Error: @SUB=TTree::SetBranchAddress
unknown branch -> ProductRegistry

----- End Fatal Exception -------------------------------------------------
[ozapatam@lxplus108 test]$ cmsRun ConfFile_cfg2.py 
----- Begin Fatal Exception 29-Jan-2018 22:17:27 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named ConfFile_cfg2.py
Exception Message:
python encountered the error: <type 'exceptions.AttributeError'>
'Process' object has no attribute 'GlobalTag'
----- End Fatal Exception -------------------------------------------------
```

por alguna razón no me reconoce el GlobalTag ni ese tag que puede ser consecuencia de no cargar el global tag(no sé).

para el global tag:
``` py
from Configuration.AlCa.GlobalTag import GlobalTag
#process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run2_mc', '')
process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:94X_mcRun2_asymptotic_v2', '') 
```
en un wiki dice que se toma del das, estaba mirado en EDM pero perdí el tiempo hasta que encontré el wiki correcto.

tengo un script de pruebas que no lo había montado por que constante mente estoy modificandolo entonces para no generar ruido
en el repo https://github.com/HENGEX/VLF_ANA/blob/cmssw-9.4.3/Dracarys/test/ConfFile_cfg2.py

pero voy hasta ahí.

Voy a seguir cacharreando y leyendo wikis, omiti un monton de otras pruebas que no vale la pena reportar por que
son pura experimentación.

Sugerencias bienvenidas :)




